---
- name: 创建临时目录
  file: dest={{ tmp_dir }} state=directory

#- name: 配置kubernetes源
#  raw: yum-config-manager --add-repo {{ kubernetes }}

- name: 配置kubernetes源
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: '0644'

- name: 安装kubelet kubeadm kubectl v2
  package:
    name:
      - "kubelet-{{ kube_version }}"
      - "kubeadm-{{ kube_version }}"
      - "kubectl-{{ kube_version }}"
    state: present

- name: 删除默认的 kubeadm 二进制文件
  file:
    path: /usr/bin/kubeadm
    state: absent

- name: "使用100年证书的 kubeadm"
  copy:
    src: "{{ tmp_dir }}/kubernetes/_output/local/go/bin/kubeadm"
    dest: "/usr/bin/kubeadm"
    mode: '0755'
    remote_src: yes  # 从目标节点复制文件

- name: 启动kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: 重置k8s系统
  shell: "kubeadm reset -f"

- name: 干掉可能存在的 kube 相关进程
  shell: |
    pids=$(ps -ef | grep -E 'kube|etcd' | grep -v grep | awk '{print $2}')
    if [ -n "$pids" ]; then
      kill -9 $pids
    fi
  ignore_errors: yes 

- name: 删除相关 kube 文件和目录
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes/
    - "{{ ansible_env.HOME }}/.kube/config"
    - /var/lib/kubelet
    - /var/lib/dockershim
    - /var/run/kubernetes
    - /var/lib/cni
    - /etc/cni/net.d

- name: 分发join脚本
  copy:
    src: "{{ tmp_dir }}/node-join.sh"
    dest: "{{ tmp_dir }}/node-join.sh"
    mode: '0755'

- name: 修改 kubelet 存储目录
  template:
    src: "kubelet.j2"
    dest: "/etc/sysconfig/kubelet"

- name: 使 kubelet 晚于 containerd 启动
  template: 
    src: "10-depend-on-containerd.conf.j2"
    dest: "/lib/systemd/system/kubelet.service.d/10-depend-on-containerd.conf"

- name: 创建 manifests 目录
  file: dest=/etc/kubernetes/manifests state=directory

- name: 加入集群
  ignore_errors: yes
  shell: "/bin/bash {{ tmp_dir }}/node-join.sh >/dev/null 2>&1"

- name: 重启 containerd 服务
  systemd:
    name: containerd
    state: restarted

- name: 重启kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes
