---
- name: 如果是 Red Hat 系统，禁用 Subscription Manager 仓库管理
  shell: |
    if [ -f /etc/redhat-release ] && grep -q "Red Hat" /etc/redhat-release; then
      subscription-manager config --rhsm.manage_repos=0
    fi
  args:
    executable: /bin/bash
  when: ansible_facts['os_family'] == 'RedHat'  # 可选，进一步确保是 RedHat 家族

- name: 备份原有的repo源
  ignore_errors: yes
  shell: mkdir -p /etc/yum.repos.d/bak && mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/bak 2>/dev/null || true

- name: 添加 YUM 仓库安装源
  raw: "{{ item }}"
  with_items:
    - "curl -o /etc/yum.repos.d/CentOS-Base.repo {{ base_repo }}"
    - "curl -o /etc/yum.repos.d/epel.repo {{ epel_repo }}"

- name: 添加 glusterfs 源
  copy:
    src: glusterfs.repo
    dest: /etc/yum.repos.d/glusterfs.repo
    mode: '0644'

- name: yum makecache 更新缓存
  raw: "{{ item }}"
  with_items:
    - "yum clean all"
    - "yum makecache fast -y"
